### PR TITLE
update to use customize framework

### PR DESCRIPTION
**Pull request by jeffbowman**
added defcustom calls to allow customization via the emacs customize framework.

### CODE REVIEW

**Comment by josteink** [comment]
Thanks. That looks really nice and like a good improvement.

If I were to be picky about something, would you mind including tips about using these customizations to `README.org` (basically just `M-x customize-group<RET>wsd-mode`)? It's nice highlighting features which are available after all.

Besides that one area I'm all ready to merge :)

**Comment by jeffbowman** [comment]
Yes, I'd be happy to do that. I should have thought of that myself, but
I'll get it done momentarily.



Amateurs work until they get it right...
... Professionals work until they can't get it wrong.

On Wed, Aug 12, 2015 at 3:29 PM, Jostein Kjønigsen <notifications@github.com

**Comment by jeffbowman** [comment]
Missed the wsd-indent-offset variable the first time, so added it this time (caught it when updating the readme). Also updated the header comment with version 0.4.0 and modified date (a bit presumptious on my part perhaps, please change as you see fit)

**Comment by josteink** [comment]
No problem. It's a new feature. It's worth a new version :)

**Comment by josteink** [comment]
And thanks for the contribution. It's very much welcome!

**Comment by jeffbowman** [comment]
Welcome very much! I love this module, thanks for providing it!


Amateurs work until they get it right...
... Professionals work until they can't get it wrong.

On Wed, Aug 12, 2015 at 3:55 PM, Jostein Kjønigsen <notifications@github.com

**Pull request merged**
